<?php

namespace Vins\Platform\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistComicRepository extends EntityRepository
{
}
