<?php
use Doctrine\ORM\EntityRepository;

/**
 * CartLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartLineRepository extends EntityRepository
{
	public function getCartLineWithAllInformations($id)
	{
		$qb = $this->createQueryBuilder('cl')
				   ->where('cl.id = :id')
				   ->setParameter('id', $id)
				   ->leftJoin('c.comic', 'c')
				   ->addSelect('c')
				   
		;

		  return $qb
	    	->getQuery()
	    	->getSingleResult()
	  ;
	}
}
