<?php

namespace Vins\Platform\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComicRepository extends EntityRepository
{
	public function getComicsWithAllInformations($id)
	{
	  $qb = $this
	    ->createQueryBuilder('c')
	    ->where('c.id = :id')
   		 ->setParameter('id', $id)
	    ->leftJoin('c.artistComics', 'ac')
	    ->addSelect('ac')
	    ->leftJoin('c.image', 'i')
	    ->addSelect('i')
	    ->leftJoin('c.categories', 'cat')
	    ->addSelect('cat')
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

	public function getThe3Last()
	{
		$qb = $this->createQueryBuilder('c')
				   ->select('c')
				   ->OrderBy('c.creationDate','DESC')
				   ->setMaxResults( 3 );
	    return $qb->getQuery()->getResult();
	}


	public function research($chaine)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.title like :chaine')
                    ->orderBy('u.id')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }
}

