
client:
    path:   admin/client
    defaults: {_controller: VinsUserBundle:User:index}

client_show:
    path:   admin/client/show/{id}
    defaults: {_controller: VinsUserBundle:User:show}

client_edit:
    path:   admin/client/edit/{id}
    defaults: {_controller: VinsUserBundle:User:edit}
    
vins_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: VinsUserBundle:Default:index }
