<?php

namespace Vins\UserBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository 
{
	

	public function getOneClientWithAddresses($id)
	{
	  $qb = $this
	    ->createQueryBuilder('c')
	    ->where('c.id = :id')
   		 ->setParameter('id', $id)
	    ->leftJoin('c.adresses', 'ac')
	    ->addSelect('ac')
	  ;

	  return $qb
	    ->getQuery()
	    ->getSingleResult()
	  ;
	}

}
